# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - '**/generated_plugin_registrant.dart'
linter:
  rules:
    use_build_context_synchronously: false
    specify_nonobvious_property_types: false
