name: Publish to pub.dev

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+*" # Matches tags like 2.7.0, 2.7.0+1, etc.

jobs:
    publish:
        permissions:
            id-token: write # Required for OIDC authentication
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true
            - name: Publish to pub.dev
              run: dart pub publish --force
